modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="enhancedvanilla"
version="Snapshot 20w20a"
displayName="Enhanced Vanilla"
credits="Credits for the Suggestions from r/minecraftsuggestions"
displayURL="https://www.curseforge.com/minecraft/mc-mods/enhanced-vanilla"
logoFile="logo.png"
authors="Karogath Modding Studios"
description='''
Bringing Quality Features to Minecraft
'''

[[dependencies.enhancedvanilla]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



